### PR TITLE
v1.2.2: Moderation v2

### PR DESCRIPTION
**Pull request by greeeen-dev**
**Checklist**

- [X] My code follows the repository code of conduct.
- [x] I have tested this code to make sure it works as intended.

**Details**

Moderation logs are now logged. Users and moderators can now view account standing.

**Tests**

**Relevant issues**

### CODE REVIEW

**Comment by greeeen-dev** [comment]
whoops forgot to make it draft

**Comment by greeeen-dev** [comment]
Decided to add a Discord incident logger as a QoL feature :)

**Review by NullyIsHere — COMMENTED** [review]
How do instance admins move the actual bans? Like in LinkAll, is automatic?

**Comment by greeeen-dev** [comment]
Bans saved in `modlogs` are only for logging purposes only and won't effect actual global bans. Existing bans will continue to work fine, except they won't show up in logs.

**Review by NullyIsHere — APPROVED** [review]
Amazing!

**Pull request merged**
