### PR TITLE
v2.0.0: Nextcord rewrite, and a bunch of new features

### PR DESCRIPTION
**Pull request by greeeen-dev**
**Checklist**

- [X] My code follows the repository code of conduct.
- [X] I have tested this code to make sure it works as intended.

**Details**

This is Unifier v2, the next series of Unifier.
- Uses Nextcord instead of Novus
- Help command v2
- Rooms command v2
- Emojis command v2
- Limited room rules to up to 25 rules per room for a future update
- Added ban appeal system (admins can block this for specific users)
- Added emojis in usernames
- Added username dedupe system
- EXP system
- More Discord UI elements for ease of use
- Bans from plugins can now be removed via `u!globalunban`

**Tests**

- 100% of existing Unifier features work flawlessly on Nextcord.
- Help command v2 works as intended and is polished.
- Rooms command v2 works as intended and is polished.
- EXP system works as intended. A cooldown of 30s have been added for EXP gain after user feedback.
- Appeal command works as intended and is polished.
- Emoji tags works as intended.
- Username dedupe system works as intended.

**Relevant issues**

### CODE REVIEW

**Comment by NullyIsHere** [comment]
A cooldown config option would be cool.

**Comment by greeeen-dev** [comment]
done

**Review by NullyIsHere — APPROVED** [review]
### v2 is here!

**Comment by greeeen-dev** [comment]
:woke:

**Pull request merged**
