### PR TITLE
v1.2.3: Plugin services and QoL changes

### PR DESCRIPTION
**Pull request by greeeen-dev**
**Checklist**

- [X] My code follows the repository code of conduct.
- [x] I have tested this code to make sure it works as intended.

**Details**

Lets plugins provide content processing and protection services + QoL changes.
Also @NullyIsHere please explain how there are **THREE CONTRIBUTORS** in this PR, thanks
image

**Tests**

- Content protection: Tested until alt was globalbanned
- All embeds use Unifier red now (customizable)
- Users can now use u!badge on others

**Relevant issues**

#116, #115, #114

### CODE REVIEW

**Comment by greeeen-dev** [comment]
@NullyIsHere Can you review this only once I've worked on #121?

**Comment by greeeen-dev** [comment]
Done with #121, will add more customization to logging and reporting rq

**Comment by greeeen-dev** [comment]
we ready

**Review by NullyIsHere — APPROVED** [review]
Beep! Beep! Pres GAS GAS GAS. I STEP ON THE GAS.

**Pull request merged**
