### PR TITLE
3.5.0: Slash commands

### PR DESCRIPTION
**Pull request by greeeen-dev**
**Checklist**

- [x] My code follows the repository code of conduct.
- [x] I have tested this code to make sure it works as intended.

**Details**

Updates Unifier to use slash commands to prepare for upcoming public instance.

**Tests**

**Relevant issues**

### CODE REVIEW

**Comment by greeeen-dev** [comment]
This is pretty much done feature-wise, now we're gonna check for bugs and SVs before we merge this to main

**Review by NullyIsHere — APPROVED** [review]
So much adrenaline, maybe because i was playing 40vs40 bedwars, but, finnaly time, i remember how i joined before 0.3.0. Yes Waves, i approved the PR, no need to ask more.

**Review by NullyIsHere — APPROVED** [review]
Looks good

**Comment by greeeen-dev** [comment]
why did you have to approve twice :skull:

**Pull request merged**
