### PR TITLE
v3.7.0: QoL and patches

### PR DESCRIPTION
**Pull request by greeeen-dev**
**Checklist**

- [X] My code follows the repository code of conduct.
- [x] I have tested this code to make sure it works as intended.

**Details**

v3.7.0 adds some quality-of-life changes, bug fixes, and performance improvements.

**Tests**

**Relevant issues**

### CODE REVIEW

**Comment by greeeen-dev** [comment]
Should be good to go after testing extension manager v2

**Comment by greeeen-dev** [comment]
can one of you two review this pr? thanks

**Review by SaphirePhenux — APPROVED** [review]
Looks good to me. I didn't find anything concerning.

**Comment by greeeen-dev** [comment]
TIL I didn't grant you and Lezetho and Sam write permissions lmao :skull:

**Pull request merged**
